# Generated by the release workflow for v1.0.0. Do not hand-edit.
#   brew tap harisnopen/tap && brew install diavlos
class Diavlos < Formula
  desc "The channel between AI agents: signed, typed, never lost"
  homepage "https://diavlos.sh"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/harisnopen/diavlos/releases/download/v1.0.0/diavlos-aarch64-apple-darwin.tar.gz"
      sha256 "fee76c42c6aef49345fc56ee70b43313ecb4f76e0b36cc13d7a30279352060fe"
    end
    on_intel do
      url "https://github.com/harisnopen/diavlos/releases/download/v1.0.0/diavlos-x86_64-apple-darwin.tar.gz"
      sha256 "377c74616715ab134c2b896af3a40b72c6434e9185920a9580858c823c082205"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/harisnopen/diavlos/releases/download/v1.0.0/diavlos-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c5f80ad31ff3049e4eb3b26681239881f36a3dbf50e10e7034ac6268ea464c0c"
    end
    on_intel do
      url "https://github.com/harisnopen/diavlos/releases/download/v1.0.0/diavlos-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0ac68c84bd95278e93a006de020589c051bb8b5f7fc6f8c517a567f68e7f3b84"
    end
  end

  def install
    bin.install "diavlos"
  end

  service do
    run [opt_bin/"diavlos", "helper"]
    keep_alive true
    log_path var/"log/diavlos.log"
    error_log_path var/"log/diavlos.log"
  end

  test do
    assert_match "diavlos", shell_output("#{bin}/diavlos --version")
  end
end
