# Generated by the release workflow for v2.1.0. Do not hand-edit.
#   brew tap harisnopen/tap && brew install diavlos
class Diavlos < Formula
  desc "The channel between AI agents: signed, typed, never lost"
  homepage "https://diavlos.sh"
  version "2.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.0/diavlos-aarch64-apple-darwin.tar.gz"
      sha256 "5a5c8e31bce13821641cf06da1d3eb4df5a9f9752ca72674f30bea8c8237892f"
    end
    on_intel do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.0/diavlos-x86_64-apple-darwin.tar.gz"
      sha256 "5e0123b88e9adc5937f5bc0f14f6ff9593822407d50c975411e25fcbc1312f7c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.0/diavlos-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "526956636e304f71ecbef45f9da5f11b0a5887f3fef961d2acdf52859aaf89e5"
    end
    on_intel do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.0/diavlos-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "044a6a3589ba9d1a267cbfacaae4db0ee7e5fab10e9fc4c74c08a74cce04fb1c"
    end
  end

  def install
    bin.install "diavlos"
    prefix.install "LICENSE", "THIRD-PARTY-LICENSES.txt"
  end

  service do
    run [opt_bin/"diavlos", "helper"]
    keep_alive true
    log_path var/"log/diavlos.log"
    error_log_path var/"log/diavlos.log"
  end

  test do
    assert_match "diavlos", shell_output("#{bin}/diavlos --version")
  end
end
