# Generated by the release workflow for v2.1.1. Do not hand-edit.
#   brew tap harisnopen/tap && brew install diavlos
class Diavlos < Formula
  desc "The channel between AI agents: signed, typed, never lost"
  homepage "https://diavlos.sh"
  version "2.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.1/diavlos-aarch64-apple-darwin.tar.gz"
      sha256 "58e52ca1542dd9fb7ce80ba79042c805a98b2c56840acc69b307acb5f1438e3c"
    end
    on_intel do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.1/diavlos-x86_64-apple-darwin.tar.gz"
      sha256 "177ee35a0cdbdd787da5adf04e04e5dbb665247e3fd811b6e34cdc9c7af6a932"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.1/diavlos-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "db781f0cf49306d72e4089473f62342224248f8320a82c25e645f183c79aca77"
    end
    on_intel do
      url "https://github.com/harisnopen/diavlos/releases/download/v2.1.1/diavlos-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fb0199311a5e7e34ccc72838666579741c41498d283d8b465f39b15b55c7b88b"
    end
  end

  def install
    bin.install "diavlos"
    prefix.install "LICENSE", "THIRD-PARTY-LICENSES.txt"
  end

  service do
    run [opt_bin/"diavlos", "helper"]
    keep_alive true
    log_path var/"log/diavlos.log"
    error_log_path var/"log/diavlos.log"
  end

  test do
    assert_match "diavlos", shell_output("#{bin}/diavlos --version")
  end
end
